### PR TITLE
Changes on Base Site Structure with CSS Grid on branch Develop1

### PR DESCRIPTION
**Pull request by edmari689**
The site has constructed into grid layout. I follow the looks of Gary Sheng's website, and made good suggestive design. It has been inserted with small basic responsive design effects, but there are wrong looks of display I am trying to figure of.

### CODE REVIEW

**Comment by xuatz** [comment]
Firstly, the description should reflect the agenda of the pull request more clearly. The title probably doesnt need the branch name, we can see from the PR and shouldn't really matter anyways.

The description should tell us what is the subject of the change. "Why" if you want to provide more information but usually unnecessary. I would write something like this instead.

```
# Summary

* removed unused style
* consolidate similar style classes
* added `layout` class for base css grid structure

# Notes

I want to do ??? but I'm having some problems with it.
Please let me know if you have any ideas!

> If there a change in layout design, include some before and after screenshot to make it easier for the reviewers
> And if there is a change in layout, this should have been mentioned in the title or description
```

**Comment by xuatz** [comment]
Secondly, regarding your commit messages there are a few problems.

Generally you should summarise the commit action within the title. Only if what you did was so huge and you needed to elaborate on them, then you use more lines.

These are not laws but just good guidelines to follow:
  * https://chris.beams.io/posts/git-commit/

 

Example:
```
Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical (unless
you omit the body entirely); various tools like `log`, `shortlog`
and `rebase` can get confused if you run the two together.

Explain the problem that this commit is solving. Focus on why you
are making this change as opposed to how (the code explains that).
Are there side effects or other unintuitive consequences of this
change? Here's the place to explain them.

Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded
   by a single space, with blank lines in between, but conventions
   vary here

If you use an issue tracker, put references to them at the bottom,
like this:

Resolves: #123
See also: #456, #789
```

Why 50 characters for subject and 72 characters for body? It is due to legacy reasons as most terminals are typically 80 characters wide, so by doing so you can be sure the formatting is as you expected it.
As a result of this, it has become a convention and there are many tools in the git ecosystem that works around these values such as command line tools, git servers like github and gitlab, git blame, editor plugins etc etc.

**Comment by edmari689** [comment]
Thank you for commenting, Xuatz. I will try to add changes with good information.

**Comment by edmari689** [comment]
I have left and updated changes on pushing commits to this branch:

Summary 

* Added photos
* Positioned div groups on education and hobbies sections
* Rewrote texts on education and hobbies sections

Notes

Images are basically set in responsive look, but these may not look good when changing device view to unusual display.
Please let me know if you have nice suggestions.

**Comment by xuatz** [comment]
I guess you can close this for #2?

**Pull request closed without merging**
